version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rst-cleantech"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w0wxihb8k5i6"
s3_prefix = "rst-cleantech"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BoardTable=\"Boards_data\""
image_repositories = []
